## This file was created automatically, do not edit by hand.


#' Very wet days wrt 95th percentile of reference period
#' 
#' Let infile1 be a time series RR of the daily precipitation amount at wet days
#' (precipitation \>= 1 mm) and infile2 be the 95th percentile RRn95 of the daily
#' precipitation amount at wet days for any period used as reference. Then the
#' percentage of wet days with RR \> RRn95 is calculated. RRn95 is calculated as
#' the 95th percentile of all wet days of a given climate reference period.
#' Usually infile2 is generated by the operator ydaypctl,95. The date information
#' of a timestep in outfile is the date of the last contributing timestep in
#' infile1.
#' 
#' @details
#'      contour  Contour plot
#'               The operator contour generates the discrete contour lines of the input field values.
#'               The following additional parameters are valid for contour operator,
#'               module in addition to the common plot parameters:
#' 
#' @name EcaR95p
NULL

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname EcaR95p
#' @export 
cdo_eca_r95p <- new_operator("eca_r95p", 2, 1)

