## This file was created automatically, do not edit by hand.


#' Monthly arithmetic
#' 
#' This module performs simple arithmetic of a time series and one timestep with
#' the same month and year. For each field in infile1 the corresponding field of
#' the timestep in infile2 with the same month and year is used. The header
#' information in infile1 have to be the same as in infile2. Usually infile2 is
#' generated by an operator of the module MONSTAT.
#' 
#' @details
#'      monadd  Add monthly time series
#'              Adds a time series and a monthly time series.
#'      monsub  Subtract monthly time series
#'              Subtracts a time series and a monthly time series.
#'      monmul  Multiply monthly time series
#'              Multiplies a time series and a monthly time series.
#'      mondiv  Divide monthly time series
#'              Divides a time series and a monthly time series.
#' 
#' @name Monarith
NULL

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Monarith
#' @export 
cdo_monadd <- new_operator("monadd", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Monarith
#' @export 
cdo_mondiv <- new_operator("mondiv", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Monarith
#' @export 
cdo_monmul <- new_operator("monmul", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Monarith
#' @export 
cdo_monsub <- new_operator("monsub", 2, 1)

