## This file was created automatically, do not edit by hand.


#' Multi-year daily arithmetic
#' 
#' This module performs simple arithmetic of a time series and one timestep with
#' the same day of year. For each field in infile1 the corresponding field of the
#' timestep in infile2 with the same day of year is used. The header information
#' in infile1 have to be the same as in infile2. Usually infile2 is generated by
#' an operator of the module YDAYSTAT.
#' 
#' @details
#'      ydayadd  Add multi-year daily time series
#'               Adds a time series and a multi-year daily time series.
#'      ydaysub  Subtract multi-year daily time series
#'               Subtracts a time series and a multi-year daily time series.
#'      ydaymul  Multiply multi-year daily time series
#'               Multiplies a time series and a multi-year daily time series.
#'      ydaydiv  Divide multi-year daily time series
#'               Divides a time series and a multi-year daily time series.
#' 
#' @name Ydayarith
NULL

#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ydayarith
#' @export
cdo_ydayadd <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ydayadd', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ydayarith
#' @export
cdo_ydayadd <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ydayadd', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ydayarith
#' @export
cdo_ydaydiv <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ydaydiv', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ydayarith
#' @export
cdo_ydaydiv <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ydaydiv', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ydayarith
#' @export
cdo_ydaymul <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ydaymul', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ydayarith
#' @export
cdo_ydaymul <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ydaymul', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ydayarith
#' @export
cdo_ydaysub <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ydaysub', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ydayarith
#' @export
cdo_ydaysub <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ydaysub', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
