## This file was created automatically, do not edit by hand.


#' Multi-year daily arithmetic
#' 
#' This module performs simple arithmetic of a time series and one timestep with
#' the same day of year. For each field in infile1 the corresponding field of the
#' timestep in infile2 with the same day of year is used. The header information
#' in infile1 have to be the same as in infile2. Usually infile2 is generated by
#' an operator of the module YDAYSTAT.
#' 
#' @details
#'      ydayadd  Add multi-year daily time series
#'               Adds a time series and a multi-year daily time series.
#'      ydaysub  Subtract multi-year daily time series
#'               Subtracts a time series and a multi-year daily time series.
#'      ydaymul  Multiply multi-year daily time series
#'               Multiplies a time series and a multi-year daily time series.
#'      ydaydiv  Divide multi-year daily time series
#'               Divides a time series and a multi-year daily time series.
#' 
#' @name Ydayarith
NULL

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Ydayarith
#' @export 
cdo_ydayadd <- new_operator("ydayadd", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Ydayarith
#' @export 
cdo_ydaydiv <- new_operator("ydaydiv", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Ydayarith
#' @export 
cdo_ydaymul <- new_operator("ydaymul", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Ydayarith
#' @export 
cdo_ydaysub <- new_operator("ydaysub", 2, 1)

