## This file was created automatically, do not edit by hand.


#' Multi-year hourly arithmetic
#' 
#' This module performs simple arithmetic of a time series and one timestep with
#' the same hour and day of year. For each field in infile1 the corresponding
#' field of the timestep in infile2 with the same hour and day of year is used.
#' The header information in infile1 have to be the same as in infile2. Usually
#' infile2 is generated by an operator of the module YHOURSTAT.
#' 
#' @details
#'      yhouradd  Add multi-year hourly time series
#'                Adds a time series and a multi-year hourly time series.
#'      yhoursub  Subtract multi-year hourly time series
#'                Subtracts a time series and a multi-year hourly time series.
#'      yhourmul  Multiply multi-year hourly time series
#'                Multiplies a time series and a multi-year hourly time series.
#'      yhourdiv  Divide multi-year hourly time series
#'                Divides a time series and a multi-year hourly time series.
#' 
#' @name Yhourarith
NULL

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Yhourarith
#' @export 
cdo_yhouradd <- new_operator("yhouradd", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Yhourarith
#' @export 
cdo_yhourdiv <- new_operator("yhourdiv", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Yhourarith
#' @export 
cdo_yhourmul <- new_operator("yhourmul", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Yhourarith
#' @export 
cdo_yhoursub <- new_operator("yhoursub", 2, 1)

