## This file was created automatically, do not edit by hand.


#' Multi-year monthly arithmetic
#' 
#' This module performs simple arithmetic of a time series and one timestep with
#' the same month of year. For each field in infile1 the corresponding field of
#' the timestep in infile2 with the same month of year is used. The header
#' information in infile1 have to be the same as in infile2. Usually infile2 is
#' generated by an operator of the module YMONSTAT.
#' 
#' @details
#'      ymonadd  Add multi-year monthly time series
#'               Adds a time series and a multi-year monthly time series.
#'      ymonsub  Subtract multi-year monthly time series
#'               Subtracts a time series and a multi-year monthly time series.
#'      ymonmul  Multiply multi-year monthly time series
#'               Multiplies a time series and a multi-year monthly time series.
#'      ymondiv  Divide multi-year monthly time series
#'               Divides a time series and a multi-year monthly time series.
#' 
#' @name Ymonarith
NULL

#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ymonarith
#' @export
cdo_ymonadd <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ymonadd', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ymonarith
#' @export
cdo_ymonadd <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ymonadd', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ymonarith
#' @export
cdo_ymondiv <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ymondiv', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ymonarith
#' @export
cdo_ymondiv <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ymondiv', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ymonarith
#' @export
cdo_ymonmul <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ymonmul', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ymonarith
#' @export
cdo_ymonmul <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ymonmul', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ymonarith
#' @export
cdo_ymonsub <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ymonsub', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Ymonarith
#' @export
cdo_ymonsub <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'ymonsub', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
