## This file was created automatically, do not edit by hand.


#' Multi-year seasonal arithmetic
#' 
#' This module performs simple arithmetic of a time series and one timestep with
#' the same season. For each field in infile1 the corresponding field of the
#' timestep in infile2 with the same season is used. The header information in
#' infile1 have to be the same as in infile2. Usually infile2 is generated by an
#' operator of the module YSEASSTAT.
#' 
#' @details
#'      yseasadd  Add multi-year seasonal time series
#'                Adds a time series and a multi-year seasonal time series.
#'      yseassub  Subtract multi-year seasonal time series
#'                Subtracts a time series and a multi-year seasonal time series.
#'      yseasmul  Multiply multi-year seasonal time series
#'                Multiplies a time series and a multi-year seasonal time series.
#'      yseasdiv  Divide multi-year seasonal time series
#'                Divides a time series and a multi-year seasonal time series.
#' 
#' @name Yseasarith
NULL

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Yseasarith
#' @export 
cdo_yseasadd <- new_operator("yseasadd", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Yseasarith
#' @export 
cdo_yseasdiv <- new_operator("yseasdiv", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Yseasarith
#' @export 
cdo_yseasmul <- new_operator("yseasmul", 2, 1)

#' @param input_file_1,input_file_2 input files.
#' @param output_file output file.
#' @rdname Yseasarith
#' @export 
cdo_yseassub <- new_operator("yseassub", 2, 1)

