## This file was created automatically, do not edit by hand.


#' Multi-year seasonal arithmetic
#' 
#' This module performs simple arithmetic of a time series and one timestep with
#' the same season. For each field in infile1 the corresponding field of the
#' timestep in infile2 with the same season is used. The header information in
#' infile1 have to be the same as in infile2. Usually infile2 is generated by an
#' operator of the module YSEASSTAT.
#' 
#' @details
#'      yseasadd  Add multi-year seasonal time series
#'                Adds a time series and a multi-year seasonal time series.
#'      yseassub  Subtract multi-year seasonal time series
#'                Subtracts a time series and a multi-year seasonal time series.
#'      yseasmul  Multiply multi-year seasonal time series
#'                Multiplies a time series and a multi-year seasonal time series.
#'      yseasdiv  Divide multi-year seasonal time series
#'                Divides a time series and a multi-year seasonal time series.
#' 
#' @name Yseasarith
NULL

#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Yseasarith
#' @export
cdo_yseasadd <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'yseasadd', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Yseasarith
#' @export
cdo_yseasadd <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'yseasadd', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Yseasarith
#' @export
cdo_yseasdiv <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'yseasdiv', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Yseasarith
#' @export
cdo_yseasdiv <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'yseasdiv', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Yseasarith
#' @export
cdo_yseasmul <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'yseasmul', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Yseasarith
#' @export
cdo_yseasmul <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'yseasmul', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Yseasarith
#' @export
cdo_yseassub <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'yseassub', 
            inputs = list(infile1), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
#' @param infile1,infile2 input files.
#' @param outfile output file.
#' @rdname Yseasarith
#' @export
cdo_yseassub <- function(infile1, infile2, outfile = NULL) {
  .new_step(operator = 'yseassub', 
            inputs = list(infile2), 
            outputs = c(outfile), 
            n_inputs = 2,
            n_outputs = 1)
}
